platform :ios, '13.0'

source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'DolyameSDKUsageDemo' do
  project 'DolyameSDKUsageDemo_Partners'

  pod 'DolyameSDK', path: '../'
  pod 'SnapKit'
end
