---

name: DolyameSDKUsageDemo_Partners
settings:
  DEVELOPMENT_TEAM: Z8MAVG5W47
  ENABLE_BITCODE: false

targets:
  DolyameSDKUsageDemo:
    scheme: {}
    type: application
    platform: iOS
    deploymentTarget: "12.3"
    sources: [DolyameSDKUsageDemo]
    settings:
      base:
        MARKETING_VERSION: 1.0.17
        CURRENT_PROJECT_VERSION: 1
        BUILD_LIBRARY_FOR_DISTRIBUTION: true
        PRODUCT_BUNDLE_IDENTIFIER: ru.tcsenterprise.core.ios.dolyamesdk
        TARGETED_DEVICE_FAMILY: 1
        DEVELOPMENT_TEAM: Z8MAVG5W47
      configs:
        Debug:
          PROVISIONING_PROFILE_SPECIFIER: "match Development ru.tcsenterprise.core.ios.dolyamesdk"
          CODE_SIGN_IDENTITY: "Apple Development: iOS Automation (32CR662BJU)"
        Release:
          PROVISIONING_PROFILE_SPECIFIER: "match InHouse ru.tcsenterprise.core.ios.dolyamesdk"
          CODE_SIGN_IDENTITY: "iPhone Distribution: TINKOFF TSENTR RAZRABOTKI, OOO"
